# NumPy:-

In [2]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

In [8]:
np.array([1,553,3,45,66,77])

array([  1, 553,   3,  45,  66,  77])

In [12]:
l1=[1,553,344,56,77,78]
arr=np.array(l1)
print(arr)

[  1 553 344  56  77  78]


In [14]:
type(arr)

numpy.ndarray

In [24]:
#2d Array
arr2=np.array([[2,3,45,56],[33,45,67,87]])
print(arr2)

[[ 2  3 45 56]
 [33 45 67 87]]


# Data type:-

In [27]:
np.array([33,45,34,67,56],dtype=float)

array([33., 45., 34., 67., 56.])

In [29]:
np.array([33,45,34,67,56],dtype=complex)

array([33.+0.j, 45.+0.j, 34.+0.j, 67.+0.j, 56.+0.j])

In [31]:
np.array([33,45,34,67,56],dtype=bool)

array([ True,  True,  True,  True,  True])

In [33]:
print(l1)

[1, 553, 344, 56, 77, 78]


In [39]:
print(l1)
print(type(l1))
print(arr)
print(type(arr))

[1, 553, 344, 56, 77, 78]
<class 'list'>
[  1 553 344  56  77  78]
<class 'numpy.ndarray'>


# arange:-

In [43]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
np.arange(3.0)

array([0., 1., 2.])

In [51]:
np.arange(0,4)

array([0, 1, 2, 3])

In [55]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [57]:
np.arange(33.40)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33.])

In [61]:
np.arange(-10,10)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [63]:
np.arange(-20,30)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29])

In [65]:
np.arange()

TypeError: arange() requires stop to be specified.

In [67]:
np.arange(0,30,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [69]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

# Zeros:-

In [78]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
n=(7,8)
np.zeros(n)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

# ones:-

In [86]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
np.ones(12,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [90]:
np.ones(12,dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [98]:
print(n)
np.ones(n)

(7, 8)


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

# Reshape:-

In [104]:
np.arange(1,9).reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [118]:
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# line sapce:-

In [127]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# identity:-

*Digonal elements are 1,remaining0

In [130]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#  Array attributes:-

In [147]:
a1=np.arange(20)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [155]:
a2=np.arange(12,dtype=float).reshape(2,6)
a2

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]])

In [159]:
a3=np.arange(12).reshape(2,2,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])